# This is a basic workflow to help you get started with Actions

name: SGSI_Build

on:
  watch:
    types: [started]
    
env:              
  ROM_URL: https://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus6Oxygen/OnePlus6Oxygen_22.J.53_GLO_053_2104202241/OnePlus6Oxygen_22.J.53_OTA_053_all_2104202241_ecefb.zip
  ZIP_NAME: test.zip
  OS_TYPE: oneplus
  BUILD_TYPE: 'ab'
  REPACK_NAME: build_action.zip
  VERSION: 12
  upload_WeTransfer: 'true'
  upload_action-gh-release: 'false'
  SETUP: 'true'
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the SPICES
         run: |
            sudo apt-get install -y git openjdk-8-jdk wget git zip unzip curl
       - name: Cloning...
         run: |
             git clone https://github.com/SmPriyo/PriyoSGSIs.git -b 11 PriyoSGSIs
           
       - name: Download zip...
         run: |
            cd PriyoSGSIs
            mkdir ./tmp
            cd ./tmp
            sudo wget $ROM_URL -O $ZIP_NAME && ls
            
       - name: Setup Tool Utils...
         if: env.SETUP == 'true'
         run: |
            sudo bash ./setup.sh

       - name: Building AB DEVICES SGSI...
         cd PriyoSGSIs
         if: env.BUILD_TYPE == 'AB' || env.BUILD_TYPE == 'ab'
         run: |
            sudo bash ./make.sh --AB $ZIP_NAME --fix-bug

       - name: Building A-only DEVICES SGSI...
         if: env.BUILD_TYPE == 'a-only'
         run: |
            sudo bash ./make.sh --a-only $ZIP_NAME --fix-bug
           
       - name: Repack output file ...
         run: |            
             cd PriyoSGSIs
             pwd
             zip -r $REPACK_NAME ./SGSI/*
             ls "$REPACK_NAME"
       - name: Upload SGSI to WeTransfer...
         if: env.upload_WeTransfer == 'true' 
         run: |
           cd PriyoSGSIs
           pwd
           ls "$REPACK_NAME"
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet ./$REPACK_NAME
